"""Anisotropic class anchors: C orthonormal vectors in R^784, shared across clients.

Generated from a public seed -- no real data, no per-client variation.
"""
from __future__ import annotations
import torch


def make_anchors(num_classes: int = 10, anchors_per_class: int = 1,
                 input_dim: int = 784, scale: float = 3.0,
                 within_class_cos: float = 0.0,
                 seed: int = 0, device=None) -> tuple[torch.Tensor, torch.Tensor]:
    """Return (Z, y) where Z is (K*C, input_dim) and y is (K*C,) class labels.

    Anchors are generated by mixing:
      z_{k,j} = ρ · c_k + sqrt(1-ρ²) · n_{k,j}
    where c_k is an orthonormal centroid (one per class), n_{k,j} is a unit
    vector orthogonal to c_k (and to other centroids), and ρ = within_class_cos.

    All anchors then scaled to length `scale`.

    Geometric guarantees (after normalisation):
      within-class cosine  = ρ² + (1-ρ²) · 0  = ρ²  (since n vectors are orth to c)
                          Wait actually: <z1,z2> = ρ² ||c||² + (1-ρ²) <n1,n2>
                          since n1, n2 are orthogonal random unit vectors in
                          a (d-C)-dim subspace, <n1,n2> ≈ 0 in expectation.
                          So mean within-class cosine ≈ ρ².
      between-class cosine = ρ² <c_k,c_k'> + ... = 0  (centroids orthonormal,
                          n vectors orthogonal across classes).

    Examples (input_dim=784, num_classes=10):
      ρ=0   → orthonormal everything (legacy)
      ρ=0.5 → within ≈ 0.25, between ≈ 0
      ρ=0.8 → within ≈ 0.64, between ≈ 0
      ρ=1.0 → all K_a anchors per class collapse onto centroid (no within-class
              variance; same as K_a=1 effectively)

    Requires K*C <= input_dim (we need orthonormal noise basis in (d - C) dims).
    """
    K = anchors_per_class
    C = num_classes
    rho = within_class_cos
    n_total = K * C
    assert n_total <= input_dim, f"K*C={n_total} must be <= input_dim={input_dim}"
    assert 0.0 <= rho <= 1.0, "within_class_cos must be in [0,1]"
    g = torch.Generator(device="cpu").manual_seed(seed)

    if rho == 0.0:
        # legacy orthonormal-everything regime
        raw = torch.randn(input_dim, n_total, generator=g)
        Q, _ = torch.linalg.qr(raw)
        Z = Q.T * scale
    else:
        # First C columns are class centroids (orthonormal). Remaining
        # n_total - C columns are noise basis (orthonormal to centroids
        # and to each other). All from a single QR.
        raw = torch.randn(input_dim, n_total, generator=g)
        Q, _ = torch.linalg.qr(raw)             # (d, n_total), orthonormal
        centroids = Q[:, :C].T                  # (C, d), unit norm
        noise = Q[:, C:].T                      # (n_total - C, d), unit norm

        # We have C centroids and need K noise vectors per class.
        # Build per-class noise pool: total per class = K, so first K-1 noise
        # vectors per class come from the noise pool, plus one "zero noise"
        # slot for the centroid itself. So we need (K-1)*C noise vectors.
        # Layout: class k gets indices [k*K : (k+1)*K], with j=0 being the
        # pure centroid (noise = 0).
        Z = torch.zeros(n_total, input_dim)
        ni = 0
        for k in range(C):
            for j in range(K):
                if j == 0:
                    n_vec = torch.zeros(input_dim)
                else:
                    if ni < noise.size(0):
                        n_vec = noise[ni]
                        ni += 1
                    else:
                        # Ran out of orthonormal noise — fall back to a fresh
                        # Gaussian projected orthogonal to centroid k. Won't
                        # be orthogonal to other noise vectors, but for K*C
                        # not enormously larger than d this is rare.
                        xi = torch.randn(input_dim, generator=g)
                        xi = xi - centroids[k] * (xi @ centroids[k])
                        n_vec = xi / (xi.norm() + 1e-8)
                z = rho * centroids[k] + ((1 - rho ** 2) ** 0.5) * n_vec
                Z[k * K + j] = z

        # Normalise each row to unit length then scale (so pure-centroid rows
        # with j=0 don't get scale^2/||z|| weirdness; all rows have length=scale)
        Z = Z / (Z.norm(dim=1, keepdim=True) + 1e-12)
        Z = Z * scale

    y = torch.arange(C).repeat_interleave(K)
    if device is not None:
        Z = Z.to(device); y = y.to(device)
    return Z, y
